from __future__ import annotations

ENRICH_SYSTEM_PROMPT = ("You are a strict JSON generator that analyzes a list of models and returns "
      "concise metadata.\n"
      "Only respond with a single JSON object, no markdown, no extra text.\n\n"
      "## LLM Model Types"
      "For your knowledge here are LLM model types and what they mean:\n\n"
      "| Type          | Full Name / Meaning          | Input → Output                   | Typical Use Case                          |\n"
      "|---------------|------------------------------|----------------------------------|-------------------------------------------|\n"
      "| llm           | Large Language Model         | Text → Text                      | Chatbots, coding assistants, reasoning    |\n"
      "| vlm           | Vision-Language Model        | Image + Text → Text              | Visual Q&A, captioning, multimodal agents |\n"
      "| embedder      | Embedding Model              | Text → Vector (numeric array)    | Semantic search, retrieval, RAG           |\n"
      "| reranker      | Reranking Model              | Query + Candidates → Ranked list | Improving search or RAG results           |\n"
      "| tts           | Text-to-Speech               | Text → Audio                     | Generate spoken output, voice synthesis   |\n"
      "| asr           | Automatic Speech Recognition | Audio → Text                     | Transcribe recordings or live speech      |\n"
      "| diarize       | Speaker Diarization          | Audio → Speaker segments         | Detect who spoke when in audio            |\n"
      "| cv            | Computer Vision              | Image → Labels / Features        | Object detection, classification          |\n"
      "| image_gen     | Image Generation             | Text → Image                     | Generative art, visual assistants         |\n")

ENRICH_USER_PROMPT = (
        "Given the following JSON array 'models', generate detailed metadata for each model.\n"
        "\n"
        "Return EXACTLY this JSON structure and nothing else:\n"
        "{\n"
        "  \"enriched\": [\n"
        "    {\n"
        "      \"model\": \"<exact id from input>\",\n"
        "      \"server_port\": <port from input>,\n"
        "      \"summary\": \"<very short description of this specific model>\",\n"
        "      \"types\": [\"llm\" | \"vlm\" | \"embedder\" | \"reranker\" | \"tts\" | \"asr\" | \"diarize\" | \"cv\" | \"image_gen\"],\n"
        "    },\n"
        "    ... one entry per input model, in the same order ...\n"
        "  ]\n"
        "}\n"
        "Rules:\n"
        "- Include EVERY input model exactly once.\n"
        "- Use ONLY the allowed type tokens.\n"
        "- Keep summaries concise.\n"
        "- Never add extra top-level keys.\n"
        "- Never wrap your answer in markdown.\n"
        "\n"
        "Input 'models' follow (JSON array):"
    )